version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
      - "1883:1883"    # MQTT
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
